language: ruby
rvm:
  - 2.2.6
  - 2.3.3
services:
  - postgresql
before_script:
  - cp config/database.travis.yml config/database.yml
  - psql -c 'create database spa_backend_test;' -U postgres
  - "bundle exec rake db:migrate"
